GET http://localhost:3001/api/transactions/

###
GET http://localhost:3001/api/transactions/65d1b941de795db4db799232

###
GET http://localhost:3001/api/transactions/category/Drinks

###
GET http://localhost:3001/api/transactions/categories

###
POST http://localhost:3001/api/transactions/
Content-Type: application/json

{
  "date": "2024-02-12",
  "category": "Food",
  "amount": 15,
  "description": "Cream"
}
###
POST http://localhost:3001/api/transactions/categories
Content-Type: application/json

{
  "name": "Food"
}

###
POST http://localhost:3001/api/transactions/
Content-Type: application/json

{
  "date": "2024-02-26",
  "category": "drinks"
  "amount": 25,
  "description": "Whiskey"
}

###
PUT http://localhost:3001/api/transactions/65c90c2ca26b9f10b9bf1654
Content-Type: application/json

{
  "date": "2024-02-16",
  "category": "Guns",
  "amount": 500,
  "payee": "Blackwater",
  "description": "Rocket Launcher",
  "payer":"Dad"
}

###
DELETE http://localhost:3001/api/transactions/65c90c2ca26b9f10b9bf1654
#
